#!/bin/bash

run_step() {
    local message="$1"
    local command="$2"

    echo "🔄 $message"
    if eval "$command"; then
        echo "✅ $message completed successfully"
    else
        echo "❌ $message failed"
        exit 1
    fi
}

run_step "Check lint" "yarn lint"
run_step "Format code" "yarn format"
