#!/bin/bash

green() { echo "\033[32m$1\033[0m"; }
red() { echo "\033[31m$1\033[0m"; }

run_step() {
    local message="$1"
    local command="$2"

    green "🔄 $message"
    if eval "$command"; then
        green "✅ $message completed successfully"
    else
        red "❌ $message failed"
        exit 1
    fi
}

run_step "Check lint" "yarn lint"
run_step "Format code" "yarn format"
